import React, { Component } from 'react';
import SearchPanel from './components/SearchPanel/SearchPanel';
import BookCardList from './components/BookCardList/BookCardList';
import {
  BookCard,
  BookCardResponseBooks,
  BookCardResponseWorks,
} from './components/BookCard/models';

interface State {
  searchTerm: string;
  searchResults: BookCard[];
}

export default class App extends Component<object, State> {
  constructor(props: object) {
    super(props);
    this.state = {
      searchTerm: '',
      searchResults: [
        {
          id: '1',
          title: '"Fantastic Mr Fox"',
          cover: '6498519',
        },
      ],
    };
  }

  onSearch = (searchTerm: string) => {
    fetch(
      `https://openlibrary.org/search.json?q=${searchTerm}&_spellcheck_count=0&limit=10&fields=key,cover_i,title,subtitle,author_name,name&mode=everything`
    )
      .then((res) => res.json())
      .then((data: BooksResponse) =>
        this.setState({ searchResults: data.docs as any })
      )
      .catch((err) => console.log(err));
  };

  render() {
    return (
      <div>
        <div className="flex flex-row">
          <SearchPanel onSearch={this.onSearch} />
        </div>
        <div>
          <BookCardList books={this.state.searchResults} />
        </div>
      </div>
    );
  }
}
// Generated by https://quicktype.io

export interface BooksResponse {
  numFound: number;
  start: number;
  numFoundExact: boolean;
  docs: Doc[];
  num_found: number;
  q: string;
  offset: null;
}

export interface Doc {
  key: string;
  title: string;
  cover_i?: number;
  author_name: string[];
}
